"""create survey tables

Revision ID: 803d2d3472ef
Revises: db3d960c461a
Create Date: 2025-06-13 22:37:11.332160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '803d2d3472ef'
down_revision: Union[str, None] = 'db3d960c461a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('winner_option_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surveys_id'), 'surveys', ['id'], unique=False)
    op.create_table('survey_options',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('order_position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_options_id'), 'survey_options', ['id'], unique=False)
    op.create_table('survey_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['survey_options.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_votes_id'), 'survey_votes', ['id'], unique=False)
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('purchase_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expiration_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('subscription_state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latest_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('auto_renewing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledgement_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('price_nanos', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('base_plan_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linked_purchase_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    sa.UniqueConstraint('purchase_token', name='subscriptions_purchase_token_key')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    op.drop_index(op.f('ix_survey_votes_id'), table_name='survey_votes')
    op.drop_table('survey_votes')
    op.drop_index(op.f('ix_survey_options_id'), table_name='survey_options')
    op.drop_table('survey_options')
    op.drop_index(op.f('ix_surveys_id'), table_name='surveys')
    op.drop_table('surveys')
    # ### end Alembic commands ###
