"""add survey tables

Revision ID: ec4328e54b9a
Revises: c9bed5940bc4
Create Date: 2025-06-13 22:28:55.865098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec4328e54b9a'
down_revision: Union[str, None] = 'c9bed5940bc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('purchase_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expiration_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('subscription_state', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('latest_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('region_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('auto_renewing', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('acknowledgement_state', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('price_nanos', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('base_plan_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('linked_purchase_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    sa.UniqueConstraint('purchase_token', name='subscriptions_purchase_token_key')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_id', 'subscriptions', ['id'], unique=False)
    # ### end Alembic commands ###
